spring:
  datasource:
    url: #provide the url of the database 
    username: #username to access database
    password: #password to access database

  mail:
    host: smtp.gmail.com
    port: 587
    username:  #provide the email from which the emails will be sent
    password: #provide the password for this email
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO

server:
  port: 8080

app:
  jwt:
    secret: # secret key which will be used to generate jwtToken

  base-url: # provide base url (http://localhost:8080 was used)
  email-from: # specify from which email address will be sent
  email-from-name: # specify the name which will be displayed when sending email 