spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/moviewebapp
    username: levi
    password: ackerman

  mail:
    host: smtp.gmail.com
    port: 587
    username: v.shepel158@gmail.com
    password: qtlwihuusunppdhj
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO

server:
  port: 8080

app:
  jwt:
    secret: h9MzEb9WR6kz5Lhz8McrHzBCn0Z7E9nsOdfUZ3C48mA=

  base-url: http://localhost:8080
  email-from: v.shepel158@gmail.com
  email-from-name: TitanCinema


